name: custom_paints
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  intl: ^0.17.0
  isar: ^3.0.0-dev.8
  isar_flutter_libs: ^3.0.0-dev.8
  logger: ^1.1.0
  path: ^1.8.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.0-dev.8
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
